---
- name: target directory exists and is writeable
  file: path={{ target_directory }} state=directory mode=755

- name: check if archive already downloaded
  stat: path={{ target_directory }}/wordpress-{{ wp_version }}.tar.gz
  register: wp_archive

- name: download and extract WordPress if not already downloaded
  unarchive:
    src=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest={{ target_directory }}
    copy=no
    creates={{ target_directory }}/wordpress
  when: not wp_archive.stat.exists

- name: extract downloaded WordPress if already downloaded
  unarchive:
    src={{ target_directory }}/wordpress-{{ wp_version }}.tar.gz
    dest={{ target_directory }}
    copy=no
    creates={{ target_directory }}/wordpress
  when: wp_archive.stat.exists

- name: Move files from wordpress folder to parent directory
  raw: mv {{ target_directory }}/wordpress/* {{ target_directory }}

- name: delete worpress folder
  file: path={{ target_directory }}/wordpress state=absent


- name: create WordPress database
  mysql_db: name={{ wp_db_name }} state=present
  when: wp_create_mysql_db

- name: create WordPress database user
  mysql_user:
    name={{ wp_db_user }}
    password={{ wp_db_password }}
    priv={{ wp_db_name }}.*:ALL
    host='localhost'
    state=present
  when: wp_create_mysql_user

- name: fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wp_salt

- name: copy WordPress config file
  template: src=wp-config.php.j2 dest={{ target_directory }}/wp-config.php
